#define CAMERA_PERSPECTIVE 1
#define MINMAX_3X3 0
#define MINMAX_3X3_ROUNDED 0
#define MINMAX_4TAP_VARYING 0
#define MINMAX_3X3_WEIGHTED 1
#define UNJITTER_CURRENT 1
#define UNJITTER_NEIGHBORHOOD 0
#define UNJITTER_REPROJECTION 0

#define INTRPL_NONE 0
#define INTRPL_CATMULL_ROM 1
#define DITHER 0
#define USE_DILATION 1
#define USE_MAX_NEIGHBOR_VELOCITY 1

#define GAUSSIAN_NEIGHBORHOOD 1

#define PHASIC_CONSTRAINT 0
#define VELOCITY_ADAPT_PHASIC_CONSTRAINT 0

#define CONSTRAINT_NONE 0
#define CONSTRAINT_CLAMP 1
#define CONSTRAINT_CLIP 0

#define VELOCITY_ADAPT_CONSTRAINT 1
#define ONLY_CONSTRAINT_CHROMA_SPACE 0

#define COLORSPACE_RGB 1
#define COLORSPACE_YCOCG 0
#define COLORSPACE_YCBCR 0

#define ENCODE_LINEAR 1
#define ENCODE_EXP 0
#define ENCODE_SUPER_EXP 0

#define JIMANEZ_ANTI_FLICKER 1
#define STACHOWIAC_ANTI_FLICKER 1

#define COLORSPACE_RESOLVE_HISTORY_BUFFER 0
#define LATE_HISTORY_COLOR_TRANSFORM 1

#define LIMIT_FEEDBACK 0
#define SCALE_AABB_BOX 0

#define CLIP_TOWARDS_CENTER 0
#define SOFT_CLIP_INDICATOR 0

#define USE_MOTION_BLUR 0

#define VELOCITY_DEBUG 0